### ISSUE TITLE
Check Version Failed: reset.path_not_found on archlinux

### ISSUE THREAD

**Issue by bsd4343** [yeongpin/cursor-free-vip#184]
❌ Check Version Failed: reset.path_not_found
ℹ️ Stack Trace: Traceback (most recent call last):
  File "reset_machine_manual.py", line 182, in check_cursor_version
    pkg_path, _ = get_cursor_paths(translator)
                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "reset_machine_manual.py", line 60, in get_cursor_paths
    raise OSError(translator.get('reset.path_not_found', path=base_path) if translator else f"找不到 Cursor 路徑: {base_path}")
OSError: reset.path_not_found

ℹ️ Cursor Version < 0.45.0, Skip Patching getMachineId


cursor version is 0.45.14, path is /opt/cursor-bin, installed from AUR

**Comment by yeongpin** [comment]
Fixed this bug in v1.7.06 , please update

**Comment by bsd4343** [comment]
still the same error after using v1.7.06, cursor version is 0.45.14, path is /opt/cursor-bin, installed from AUR

**Comment by ang3lo-azevedo** [comment]
I have the same issue

**Comment by canmi21** [comment]
try new version, avalible on [AUR](https://aur.archlinux.org/packages/cursor-free-vip-git)
