### ISSUE TITLE
[Bug]: Reset Machine ID && New errors appeared with the previous ones.

### ISSUE THREAD

**Issue by JOO012** [yeongpin/cursor-free-vip#435]
### Commit before submitting

- [x] I understand that Issues are used to provide feedback and solve problems, not to complain in the comments section, and will provide more information to help solve the problem.
- [x] I have checked the top Issue and searched for existing [open issues](https://github.com/yeongpin/cursor-free-vip/issues) and [closed issues](https://github.com/yeongpin/cursor-free-vip/issues?q=is%3Aissue%20state%3Aclosed%20), and found no similar issues.
- [x] I have filled out a short and clear title, so that developers can quickly determine the general problem when browsing the Issue list. Not "a suggestion", "stuck", etc.

### Platform

Linux x64

### Version

1.8.03

### Description

**I've been waiting since version 1.7.x to fix these issues, but they're not fixed yet but they're getting worse now.**

I'm running Linux Debian 12.10 (Bookworm) x86_64 (AMD64).

### Related log output

```shell
with sudo :

main.py:132: DeprecationWarning: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead.

ℹ️ menu.account_info_error

⚠️ Storage file not found: /root/.config/Cursor/User/globalStorage/storage.json
ℹ️ Please make sure Cursor is installed and has been run at least once

❌ Error getting file stats: Translator.get() takes 2 positional arguments but 3 were given
❌ Permission denied: /home/XXX/.config/Cursor/User/globalStorage/storage.json

❌ Cannot Read or Write Config File, Please Check File Permissions
```

**Comment by Nigel1992** [comment]
I've created a PR (#436) that should fix the Linux path and permission issues you're experiencing. The changes include:

1. Proper handling of sudo vs normal user cases
2. Case-insensitive directory detection (Cursor/cursor)
3. Detailed permission checks and error messages
4. Better file existence verification
5. Improved error handling for file corruption
6. Clear instructions for fixing permission issues

The code will now:
- Correctly detect paths whether running with sudo or not
- Handle both "Cursor" and "cursor" directory names
- Show detailed error messages with specific instructions
- Provide clear guidance on fixing permission issues

You can try the fix by:
1. Pulling the latest changes from the PR
2. Running the script again
3. If you still see permission issues, follow the detailed error messages which will now show the exact commands needed to fix the permissions

Let me know if you still experience any issues after trying the fix.

**Comment by JOO012** [comment]
still not :

──────────────────────────────────────────────────────────────────────
👤 Account Information
──────────────────────────────────────────────────────────────────────
ℹ️ Storage file found: /home/XXX/.config/Cursor/User/globalStorage/storage.json
ℹ️ File size: 2944 bytes
ℹ️ File permissions: 0o444
ℹ️ File owner: 1000
ℹ️ File group: 1000
❌ Permission denied: /home/XXX/.config/Cursor/User/globalStorage/storage.json
ℹ️ Try running: chown XXX:XXX /home/XXX/.config/Cursor/User/globalStorage/storage.json
ℹ️ And: chmod 644 /home/XXX/.config/Cursor/User/globalStorage/storage.json
✅ Storage file is valid and contains data
ℹ️ Storage file found: /home/XXX/.config/Cursor/User/globalStorage/storage.json
ℹ️ File size: 2944 bytes
ℹ️ File permissions: 0o444
ℹ️ File owner: 1000
ℹ️ File group: 1000
❌ Permission denied: /home/XXX/.config/Cursor/User/globalStorage/storage.json
ℹ️ Try running: chown XXX:XXX /home/XXX/.config/Cursor/User/globalStorage/storage.json
ℹ️ And: chmod 644 /home/XXX/.config/Cursor/User/globalStorage/storage.json
✅ Storage file is valid and contains data
2025-03-31 06:45:58,449 - cursor_acc_info - ERROR - Get subscription info failed: 401 Client Error: Unauthorized for url: https://api2.cursor.sh/auth/full_stripe_profile
2025-03-31 06:45:58,960 - cursor_acc_info - ERROR - Get usage info failed: 401 Client Error: Unauthorized for url: https://www.cursor.com/api/usage
👤 Email: XXX
⚠️ Subscription information not found

==================================================
�� Cursor Machine ID Reset Tool
==================================================
ℹ️ Checking Config File...
❌ Cannot Read or Write Config File, Please Check File Permissions

----------------------------------------------------------------------------------
Too many free trial accounts used on this machine. Please upgrade to pro. We have this limit in place to prevent abuse. Please let us know if you believe this is a mistake.

**Comment by Nigel1992** [comment]
Did you actually try to run the commands the output gave you ?
ℹ️ Try running: chown XXX:XXX /home/XXX/.config/Cursor/User/globalStorage/storage.json
ℹ️ And: chmod 644 /home/XXX/.config/Cursor/User/globalStorage/storage.json
